"""Public API for the annual loss distribution model."""

from .distributions import (
    LognormalFit,
    ParetoFit,
    PertFit,
    distribution_curve,
    distribution_mean,
    fit_lognormal,
    fit_pareto,
    fit_pert,
    frequency_work_rate,
    sample_distribution,
)
from .exceptions import AnnualLossError, ParameterValidationError, SimulationSafetyError
from .models import (
    DEFAULT_SCENARIOS,
    ConfidenceInterval,
    DistributionCurve,
    DistributionType,
    EmpiricalCDF,
    FrequencyMethod,
    LognormalParams,
    OddsParams,
    PanelStatistic,
    ParetoParams,
    PertParams,
    Scenario,
    Section,
    SimulationConfig,
    SimulationResult,
)
from .simulation import simulate_annual_loss, simulate_scenarios
from .statistics import (
    average_panel_params,
    confidence_interval,
    empirical_cdf,
    interpolate_percentile,
    panel_analytics,
)
from .validation import (
    MAX_DISTRIBUTION_ROUNDS,
    MAX_EVENTS_PER_ROUND,
    MAX_SCENARIO_ROUNDS,
    MAX_TOTAL_EVENT_DRAWS,
    MIN_SIMULATION_ROUNDS,
    TARGET_EVENT_DRAWS,
    require_valid_params,
    validate_params,
)

__all__ = [
    "DEFAULT_SCENARIOS",
    "MAX_DISTRIBUTION_ROUNDS",
    "MAX_EVENTS_PER_ROUND",
    "MAX_SCENARIO_ROUNDS",
    "MAX_TOTAL_EVENT_DRAWS",
    "MIN_SIMULATION_ROUNDS",
    "TARGET_EVENT_DRAWS",
    "AnnualLossError",
    "ConfidenceInterval",
    "DistributionCurve",
    "DistributionType",
    "EmpiricalCDF",
    "FrequencyMethod",
    "LognormalFit",
    "LognormalParams",
    "OddsParams",
    "PanelStatistic",
    "ParameterValidationError",
    "ParetoFit",
    "ParetoParams",
    "PertFit",
    "PertParams",
    "Scenario",
    "Section",
    "SimulationConfig",
    "SimulationResult",
    "SimulationSafetyError",
    "average_panel_params",
    "confidence_interval",
    "distribution_curve",
    "distribution_mean",
    "empirical_cdf",
    "fit_lognormal",
    "fit_pareto",
    "fit_pert",
    "frequency_work_rate",
    "interpolate_percentile",
    "panel_analytics",
    "require_valid_params",
    "sample_distribution",
    "simulate_annual_loss",
    "simulate_scenarios",
    "validate_params",
]
